config/routes.rb
Fsek::Application.routes.draw do
  
  
  resources :events
  resources :pages
  resources :settings
  resources :roles
  resources :users
  resources :news
  resources :vecktors do
    resources :vecktor_notices
  end

  match 'vecktorn' => 'vecktors#show' # Genväg som visar senaste vecktorn.

  devise_for :users, :skip => [:sessions]
  as :user do
    get 'login' => 'devise/sessions#new', as: :new_user_session
    post 'login' => 'devise/sessions#create', as: :user_session
    delete 'logout' => 'devise/sessions#destroy', as: :destroy_user_session
    get 'logout' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  root to: 'news#index'

  match '/:name' => 'pages#show'

end

app/models/vecktor_notice.rb
class VecktorNotice < ActiveRecord::Base
  attr_accessible :signature, :text, :title, :vecktor_id, :order_

  belongs_to :vecktor
  belongs_to :author, :class_name => :User

  # :author kan vara nil. Detta tolkas som att Sanningsministern kopierat 
  # notisen direkt ur ett mail.

  before_save :default_values 

  def default_values
    self.signature ||= self.author.to_s
  end
end

app/controllers/vecktor_notices_controller.rb
class VecktorNoticesController < ApplicationController
  skip_before_filter :authenticate_user!, :only => [:index, :show]
  load_and_authorize_resource

=begin Onödig, detta görs redan i vecktor#show
  # GET /vecktor_notices
  # GET /vecktor_notices.json
  def index
    @vecktor_notices = VecktorNotice.where :published => true

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vecktor_notices }
    end
  end
=end

  # GET /vecktor_notices/1
  # GET /vecktor_notices/1.json
  def show
    @notice = VecktorNotice.find(params[:id])
    @vecktor = @vecktor_notice.vecktor

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vecktor_notice }
    end
  end

  # GET /vecktor_notices/new
  # GET /vecktor_notices/new.json
  def new
    @vecktor_notice = VecktorNotice.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vecktor_notice }
    end
  end

  # GET /vecktor_notices/1/edit
  def edit
    @vecktor_notice = VecktorNotice.find(params[:id])
  end

  # POST /vecktor_notices
  # POST /vecktor_notices.json
  def create
    @vecktor_notice = VecktorNotice.new(params[:vecktor_notice])

    respond_to do |format|
      if @vecktor_notice.save
        format.html { redirect_to @vecktor_notice, notice: 'VecktorNotice was successfully created.' }
        format.json { render json: @vecktor_notice, status: :created, location: @vecktor_notice }
      else
        format.html { render action: "new" }
        format.json { render json: @vecktor_notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vecktor_notices/1
  # PUT /vecktor_notices/1.json
  def update
    @vecktor_notice = VecktorNotice.find(params[:id])

    respond_to do |format|
      if @vecktor_notice.update_attributes(params[:vecktor_notice])
        format.html { redirect_to @vecktor_notice, notice: 'VecktorNotice was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vecktor_notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vecktor_notices/1
  # DELETE /vecktor_notices/1.json
  def destroy
    @vecktor_notice = VecktorNotice.find(params[:id])
    @vecktor_notice.destroy

    respond_to do |format|
      format.html { redirect_to vecktor_notices_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/vecktor_notices_helper.rb
module VecktorNoticesHelper
end

app/views/vecktor_notices/_form.html.erb
<%= form_for(@vecktor) do |f| %>
  <% if @vecktor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vecktor.errors.count, "error") %> prohibited this vecktor from being saved:</h2>

      <ul>
      <% @vecktor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :year %><br />
    <%= f.text_field :year %>
  </div>
  <div class="field">
    <%= f.label :issue %><br />
    <%= f.text_field :issue %>
  </div>
  <div class="field">
    <%= f.label :editor %><br />
    <%= f.text_field :editor %>
  </div>
  <div class="field">
    <%= f.label :responsible_publisher %><br />
    <%= f.text_field :responsible_publisher %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vecktor_notices/edit.html.erb
<h1>Editing vecktor</h1>

<%= render 'form' %>

<%= link_to 'Show', @vecktor %> |
<%= link_to 'Back', vecktors_path %>

app/views/vecktor_notices/new.html.erb
<h1>New vecktor</h1>

<%= render 'form' %>

<%= link_to 'Back', vecktors_path %>

app/views/vecktor_notices/show.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<h1><%= @notice.title %></h1>
<%= raw(markdown @notice.text) %>
<p><em>
<%= @notice.author ? link_to(@notice.signature, @notice.author) : @notice.signature %>
</em></p>

<p class="controls">
<% if can? :update, @notice %>
  <%= link_to 'Ändra', edit_vecktor_notice_path(@notice) %> |
<% end %>
<% if can? :destroy, @notice %>
  <%= link_to 'Förinta', @notice, :confirm => 'Är du säker?', :method => :delete %> |
<% end %>
<%= link_to 'Tillbaka', vecktor_index_path %>
</p>

<br />