config/routes.rb
Fsek::Application.routes.draw do
  
  
  resources :events
  resources :pages
  resources :settings
  resources :roles
  resources :users
  resources :news
  resources :vecktors do
    resources :vecktor_notices
  end

  match 'vecktorn' => 'vecktors#show' # Genväg som visar senaste vecktorn.

  devise_for :users, :skip => [:sessions]
  as :user do
    get 'login' => 'devise/sessions#new', as: :new_user_session
    post 'login' => 'devise/sessions#create', as: :user_session
    delete 'logout' => 'devise/sessions#destroy', as: :destroy_user_session
    get 'logout' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  root to: 'news#index'

  match '/:name' => 'pages#show'

end

app/models/vecktor.rb
require 'fsek_settings'

class Vecktor < ActiveRecord::Base
  include FsekSettings

  attr_accessible :date, :editor_name, :publisher_name

  has_many :vecktor_notices
  belongs_to :editor,    :class_name => :User
  belongs_to :publisher, :class_name => :User

  alias :notices :vecktor_notices

  before_save :default_values # Kallback innan saker kommittas till databasen
  
  def published
    !! self[:published] # Typkast till booleskt värde.
  end

  # Gör attributet privat, typ.
  private 
  def published= val
    self[:published] = val
  end 
  public

  def publish
    self.published = true
  end

  # Överskugga så att {publisher,editor}_name uppdateras automatiskt.

  alias :old_editor=    :editor=
  alias :old_publisher= :publisher=

  def editor= usr
    self.editor_name = usr.to_s_fstyle
    self.old_editor  = usr
  end

  def publisher= usr
    self.publisher_name = usr.to_s_fstyle
    self.old_publisher  = usr
  end


  def default_values
    self.date      ||= Time.now.to_date # Vi bryr oss inte om klockslaget.
    self.year      ||= self.date.year() - Vecktor.setting(:first_year)
    if self.issue.nil?
      last_issue = Vecktor.first :order => 'date desc, issue desc'
      if last_issue.nil? or last_issue.year != self.year
        self.issue = 1
      else
        self.issue = last_issue.issue + 1
      end
   end
  end

  def to_ascii
    v_text = ''
    File.open 'app/assets/templates/vecktor' do |f|
      v_text << f.read % [self.issue, self.year,
                          self.editor    || self.editor_name, 
                          self.publisher || self.published_name]
    end
    v_text << "\n"
    vecktor_notices.each do |notice|
      v_text << notice.title.upcase + "\n\n"
      v_text << ActionController::Base.helpers.word_wrap(notice.text, 
                                                         :line_width => 80)
      v_text << "\n\n"
    end
    v_text
  end
      
    

  def to_s
    "Vecktorn, #{date}"
  end
end

app/controllers/vecktors_controller.rb
class VecktorsController < ApplicationController
  skip_before_filter :authenticate_user!, :only => [:index, :show]
  load_and_authorize_resource

  # GET /vecktors
  def index
    @vecktors = Vecktor.find :all, :order => 'date desc', 
                             :conditions  => { :published => true }
    @year_vecktors = @vecktors.group_by { |v| v.date.year }
    @sanning  = Role.where(:tag => :sanning).first.users.first
    @deadline = Vecktor.setting :deadline
  end

  # GET /vecktors/1
  def show
    # Om vi inte får nåt id-nummer, visa senaste vecktorn. (se rutten 'vecktorn')
    if params[:id]
      @vecktor = Vecktor.find(params[:id])
    else
      @vecktor = Vecktor.first :order => 'date desc'
    end

    @notices = @vecktor.notices.sort { |n| n.order_ }
   end

  # GET /vecktors/new
  def new
    @vecktor = Vecktor.new
  end

  # GET /vecktors/1/edit
  def edit
    @vecktor = Vecktor.find(params[:id])
  end

  # POST /vecktors
  def create
    @vecktor = Vecktor.new(params[:vecktor])

    if @vecktor.save
      redirect_to @vecktor, notice: 'Vecktor was successfully created.'
    else
      render action: "new"
    end
  end

  # PUT /vecktors/1
  def update
    @vecktor = Vecktor.find(params[:id])

    if @vecktor.update_attributes(params[:vecktor])
      redirect_to @vecktor, notice: 'Vecktor was successfully updated.'
    else
      render action: "edit" 
    end
  end

  # DELETE /vecktors/1
  def destroy
    @vecktor = Vecktor.find(params[:id])
    @vecktor.destroy

    redirect_to vecktors_url
  end
end

app/helpers/vecktors_helper.rb
module VecktorsHelper
end

app/views/vecktors/index.html.erb
<h1>Vecktorer</h1>

<p>
Vecktorn är F-sektionens nyhetsbrev som ges ut sent på kvällen varje läsmåndag.
</p>

<p>
Kontakta 
<%= link_to "Sanningsminister #{@sanning.real_name}", @sanning %>
om du vill ha med en notis i Vecktorn. Deadline är kl. 
<%= @deadline %>.
</p>

<ul>
<% @year_vecktors.each do |year, vecktors| %>
  <h2 id="<%= year %>">
    <%= year %>
  </h2>
  <% vecktors.each do |vecktor| %>
    <li>
      <b><%= link_to vecktor, vecktor %></b>
      (<%= link_to 'Ändra', edit_vecktor_path(vecktor) %> |
      <%= link_to 'Förinta', vecktor, confirm: 'Är du säker?', method: :delete %>)
    </li>
  <% end %>
<% end %>
</ul>

<br />

<%= link_to 'Ny vecktor', new_vecktor_path %>

app/views/vecktors/show.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<h1>Vecktorn, <%= @vecktor.date %></h1>
<p>Utgiven av F-sektionen inom TLTH. </p>
<p>Redaktör: 
  <%= @vecktor.editor ? link_to(@vecktor.editor, @vecktor.editor) : @vecktor.editor_name %>
</p>
<p>Ansvarig Utgivare:
  <%= @vecktor.publisher ? link_to(@vecktor.publisher, @vecktor.publisher) : @vecktor.publisher_name %>
</p>
<p>Årgång:
  <%= @vecktor.year %>,
   Nummer: 
  <%= @vecktor.issue %>
</p>

<% @vecktor.notices.each do |notice| %>
  <h2><%= notice.title %></h2>
  <%= raw(markdown notice.text) %>
  <p><em><%= notice.author ? link_to(notice.signature, notice.author) : notice.signature %></em></p>
<% end %>

<br />