config/routes.rb
Fsek::Application.routes.draw do
  
  
  resources :events
  resources :pages
  resources :settings
  resources :roles
  resources :users
  resources :news
  resources :vecktors do
    resources :vecktor_notices
  end

  match 'vecktorn' => 'vecktors#show' # Genväg som visar senaste vecktorn.

  devise_for :users, :skip => [:sessions]
  as :user do
    get 'login' => 'devise/sessions#new', as: :new_user_session
    post 'login' => 'devise/sessions#create', as: :user_session
    delete 'logout' => 'devise/sessions#destroy', as: :destroy_user_session
    get 'logout' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  root to: 'news#index'

  match '/:name' => 'pages#show'

end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :description, :tag, :title, :singular
  has_and_belongs_to_many :users

  before_save :default_values # Hade varit snyggare med before_validates, 
                              # men vi behöver self.tag.

  # Singulära roller kan bara innehas av en person åt gången.
  validates :users, :length => {:minimum => 0, :maximum => 1}, 
                    :if => :singular? 
  validates :tag,   :presence => true, 
                    :uniqueness => true

  def default_values
    self.title ||= self.tag.capitalize
    # singular ||= false, men det är redan speccat i databasen.
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  skip_before_filter :authenticate_user!, :only => [:index, :show]
  load_and_authorize_resource
  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @roles }
    end
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
    @role = Role.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/new
  # GET /roles/new.json
  def new
    @role = Role.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/1/edit
  def edit
    @role = Role.find(params[:id])
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(params[:role])

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render json: @role, status: :created, location: @role }
      else
        format.html { render action: "new" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /roles/1
  # PUT /roles/1.json
  def update
    @role = Role.find(params[:id])

    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role = Role.find(params[:id])
    @role.destroy

    respond_to do |format|
      format.html { redirect_to roles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :tag %><br />
    <%= f.text_field :tag %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing role</h1>

<%= render 'form' %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<% @roles.each do |role| %>
  <h2 class="roles-index" id="<%= id_escape role.tag %>">
    <%= role.title %>
  </h2>
  <!-- <em><%= role.tag %></td></em> -->
  <!-- <%= role.description %> -->
  <ul>
  <% role.users.each do |user| %>
    <li><%= link_to user.real_name, user %></li>
  <% end %>
  </ul>
  <p class="controls">
  <%= link_to 'Visa', role %> |
  <%= link_to 'Ändra', edit_role_path(role) %> |
  <%= link_to 'Förinta', role, confirm: 'Är du säker?', method: :delete %>
  </p>
<% end %>

<br />

<%= link_to 'Ny roll', new_role_path %>

app/views/roles/new.html.erb
<h1>New role</h1>

<%= render 'form' %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @role.title %>
</p>

<p>
  <b>Tag:</b>
  <%= @role.tag %>
</p>

<p>
  <b>Description:</b>
  <%= @role.description %>
</p>


<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>